#pragma once
#include "stdio.h"
#include "welcome.h"
#include "StoreorTakeout.h"
#include "menu.h"
#include "sidemenu.h"
#include "Payment.h"
#include "PleaseWaitForAMoment.h"
#include "menuchoice.h"
#include "additional order.h"
#include "returnmenu.h"
#include "selectlist.h"
#include "RemoveSelectMenu.h"
#include "MenuRemover.h"